[tool.pytest.ini_options]
testpaths =[
    "tests",
    "fractopo_subsampling",
    ]
addopts = "--doctest-modules --pdbcls=IPython.terminal.debugger:Pdb"
doctest_optionflags =[
    "NUMBER",
    "NORMALIZE_WHITESPACE",
    ]

filterwarnings =[]

[tool.black]
exclude = "fractopo_subsampling/_version.py"

[tool.isort]
profile = "black"
multi_line_output = 3
src_paths = ["fractopo_subsampling", "tests"]
skip = "fractopo_subsampling/_version.py"

[tool.coverage.run]
omit =[
    "fractopo_subsampling/_version.py",
    ]
